stages: 
  - build-spider
  - build-test
  - test
job-build: 
  stage: build-spider
  script: 
    - "mkdir libspider/bin/"
    - "mkdir libspider/bin/make"
    - "cd libspider/bin/make"
    - "cmake ../.."
    - "make VERBOSE=1"
    - "cd ../../.."
build-test-memory: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./build-test.sh memory
  artifacts:
    path:
        - "libspider/units-tests/libSpider2-tests/memory/bin"
build-test-containers: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./build-test.sh containers
  artifacts:
    path:
        - "libspider/units-tests/libSpider2-tests/containers/bin"
build-test-expression: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./build-test.sh expression-parser
  artifacts:
    path:
        - "libspider/units-tests/libSpider2-tests/expression-parser/bin"
test-memory: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh memory
test-containers: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh containers
test-expression: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh expression-parser
