stages: 
  - build-spider
  - test
job-build: 
  stage: build-spider
  script: 
    - "mkdir libspider/bin/"
    - "cd libspider/bin"
    - "cmake -DCMAKE_BUILD_TYPE=Debug .."
    - "make VERBOSE=1 -j$(nproc)"
    - "cd ../../"
  artifacts:
    paths:
    - "libspider/bin"
test-allocator: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh allocator
test-containers: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh containers
test-expression: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh expression
test-rpnconverter: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./run-test.sh rpnconverter
