stages: 
  - build-spider
  - build-test
  - test
job-build: 
  stage: build-spider
  script: 
    - "mkdir libspider/bin/"
    - "mkdir libspider/bin/make"
    - "cd libspider/bin/make"
    - "cmake ../.."
    - "make VERBOSE=1"
    - "cd ../../.."
build-test-memory: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./build-test.sh memory
build-test-containers: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./build-test.sh containers
build-test-expression: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/"
    - ./build-test.sh expression-parser
test-memory: 
  stage: test
  script: 
    - ./run-test.sh memory
  artifacts:
    reports:
      junit: libspider/units-tests/libSpider2-tests/memory/report-memory.xml
test-containers: 
  stage: test
  script: 
    - ./run-test.sh containers
  artifacts:
    reports:
      junit: libspider/units-tests/libSpider2-tests/containers/report-containers.xml
test-expression: 
  stage: test
  script: 
    - ./run-test.sh expression-parser
  artifacts:
    reports:
      junit: libspider/units-tests/libSpider2-tests/expression-parser/report-expression-parser.xml
