stages: 
  - build-spider
  - test
job-build: 
  stage: build-spider
  script: 
    - cd bin
    - "cmake .. -DCMAKE_BUILD_TYPE=Debug"
    - "make VERBOSE=1 -j$(nproc)"
    - "cd ../"
  artifacts:
    paths:
    - "bin"
test-allocator: 
  stage: test
  script: 
    - ./scripts/linux/runTest.sh allocator
test-containers: 
  stage: test
  script: 
    - ./scripts/linux/runTest.sh containers
test-expression: 
  stage: test
  script: 
    - ./scripts/linux/runTest.sh expression
test-rpnconverter: 
  stage: test
  script: 
    - ./scripts/linux/runTest.sh rpnconverter
test-graph: 
  stage: test
  script: 
    - ./scripts/linux/runTest.sh graph
