stages: 
  - build-spider
  - test
job-build: 
  stage: build-spider
  script: 
    - "mkdir libspider/bin/"
    - "cd libspider/bin"
    - "cmake -DCMAKE_BUILD_TYPE=Debug .."
    - "make VERBOSE=1 -j$(nproc)"
    - "cd ../../"
  artifacts:
    paths:
    - "bin"
test-allocator: 
  stage: test
  script: 
    - ./script/linux/runTest.sh allocator
test-containers: 
  stage: test
  script: 
    - ./script/linux/runTest.sh containers
test-expression: 
  stage: test
  script: 
    - ./script/linux/runTest.sh expression
test-rpnconverter: 
  stage: test
  script: 
    - ./script/linux/runTest.sh rpnconverter
test-graph: 
  stage: test
  script: 
    - ./script/linux/runTest.sh graph
