stages: 
  - build
  - build-test
  - test
job-build: 
  stage: build
  script: 
    - "mkdir libspider/bin/"
    - "mkdir libspider/bin/make"
    - "cd libspider/bin/make"
    - "cmake ../.."
    - "make VERBOSE=1"
    - "cd ../../.."
build-test-memory: 
  stage: build-test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/memory"
    - ./build-memory-test.sh
test-memory: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/memory"
    - ./run-memory-test.sh
    - "rm -rf report/"
  artifacts:
    reports:
      junit: libspider/units-tests/libSpider2-tests/memory/report-memory.xml
test-containers: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/containers"
    - ./run-containers-test.sh
    - "rm -rf report/"
  artifacts:
    reports:
      junit: libspider/units-tests/libSpider2-tests/containers/report-containers.xml
test-expression: 
  stage: test
  script: 
    - "cd libspider/units-tests/libSpider2-tests/expression-parser"
    - ./run-expression-parser-test.sh
    - "rm -rf report/"
  artifacts:
    reports:
      junit: libspider/units-tests/libSpider2-tests/expression-parser/report-expression-parser.xml
